apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
  namespace: tekton-squad-1-project
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - list
  - patch
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - patch
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - patch
  - create
- apiGroups:
  - ""
  resources:
  - networkpolicies
  verbs:
  - get
  - patch
  - create
