apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kustomize
  namespace: tekton-squad-1-project
spec:
  params:
  - description: the name of the app
    name: app-name
    type: string
  - description: namespace of the deployment
    name: app-namespace
    type: string
  - description: contains the full image repository (without :tag)
    name: image-repo
    type: string
  - description: Source git repository
    name: source-repo
    type: string
  - description: The precise commit SHA used for this task
    name: commit
    type: string
  steps:
  - image: quay.io/upslopeio/kustomize:latest
    name: kustomize-build
    resources: {}
    script: |
      #!/bin/sh

      cd source/k8s

      if [ -f kustomization.yaml ] || [ -f kustomization.yml ] || [ -f Kustomization ]; then
        echo "Kustomization file found."
      else
        echo "Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory:"
        pwd
        exit 1
      fi

      kustomize edit set image "*=$(params.image-repo):$(params.commit)"
      kustomize edit set label "app.kubernetes.io/instance:$(params.app-namespace)"
      kustomize edit set label "app.kubernetes.io/name:$(params.app-namespace)-$(params.app-name)"
      kustomize edit set label "app.openshift.io/runtime:js"
      kustomize edit set label "app:$(params.app-namespace)"

      kustomize edit add annotation "app.openshift.io/vcs-uri:$(params.source-repo)"
      kustomize edit add annotation "app.openshift.io/vcs-ref:$(params.commit)"

      kustomize build > manifests.yaml

      if [ -f manifests.yaml ]; then
        echo "manifests.yaml successfully generated"
        echo "contents of manifests is:"
        cat manifests.yaml
      else
        echo "ERROR: manifests.yaml not generated"
        exit 1
      fi
  workspaces:
  - description: contains the cloned git repo
    name: source
