apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  params:
  - description: Source code repository
    name: source-repo
  - description: Precise SHA of the commit to build
    name: sha
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: tekton-squad-1-app-pipelinerun-
      spec:
        pipelineRef:
          name: tekton-squad-1-pipeline
        serviceAccountName: build-bot
        params:
          - name: app-name
            value: next-js-app
          - name: source-repo
            value: $(tt.params.source-repo)
          - name: image-repo
            value: quay.io/jian_ping_shu/next_js
          - name: sha
            value: $(tt.params.sha)
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi

